jobs:
  build:
    docker:
      - image: cimg/rust:1.59.0
    steps:
      - checkout
      - run:
          name: Install essentials
          command: |
            sudo apt update
            sudo apt install libclang-dev -y
      - run:
          name: Compile, build and install
          command: |
            pwd
            ./setup.sh
            cargo install --path ./meta
      - run:
          name: Init substrate node template
          command: |
            cd ..
            git clone https://github.com/substrate-developer-hub/substrate-node-template
      - run:
          name: Run on substrate-node-template
          command: |
            cd ../substrate-node-template/pallets/template
            cargo saft