jobs:
  build:
    docker:
      - image: cimg/rust:1.59.0
    steps:
      - checkout
      - run:
          name: Install essentials
          command: |
            sudo apt update
            sudo apt install libclang-dev -y
      - run:
          name: Compile, build and install
          command: |
            ./scripts/setup.sh
            cargo install --path ./meta
      - run:
          name: Run unit tests
          command: |
            cargo test
      - run:
          name: Build doc
          command: |
            cargo doc --workspace
      - run:
          name: Clone and run on FRAME pallets
          command: |
            ./scripts/run_on_frame.sh