jobs:
  build:
    docker:
      - image: cimg/rust:1.45.0
    steps:
      - checkout
      - run:
          name: Compile, build and install
          command: |
            ./setup.sh
            cargo install --path ./meta
      #- run:
          #name: Init substrate node template